packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  node-liblzma: false
  protobufjs: false

catalog:
  '@iconify-json/catppuccin': ^1.2.17
  '@iconify/tailwind4': ^1.2.3
  vite-plus: ^0.2.4

minimumReleaseAgeExclude:
  - '@tiptap/core@3.31.0'
  - '@tiptap/extension-blockquote@3.31.0'
  - '@tiptap/extension-bold@3.31.0'
  - '@tiptap/extension-bubble-menu@3.31.0'
  - '@tiptap/extension-bullet-list@3.31.0'
  - '@tiptap/extension-code-block@3.31.0'
  - '@tiptap/extension-code@3.31.0'
  - '@tiptap/extension-document@3.31.0'
  - '@tiptap/extension-dropcursor@3.31.0'
  - '@tiptap/extension-floating-menu@3.31.0'
  - '@tiptap/extension-gapcursor@3.31.0'
  - '@tiptap/extension-hard-break@3.31.0'
  - '@tiptap/extension-heading@3.31.0'
  - '@tiptap/extension-horizontal-rule@3.31.0'
  - '@tiptap/extension-image@3.31.0'
  - '@tiptap/extension-italic@3.31.0'
  - '@tiptap/extension-link@3.31.0'
  - '@tiptap/extension-list-item@3.31.0'
  - '@tiptap/extension-list-keymap@3.31.0'
  - '@tiptap/extension-list@3.31.0'
  - '@tiptap/extension-ordered-list@3.31.0'
  - '@tiptap/extension-paragraph@3.31.0'
  - '@tiptap/extension-strike@3.31.0'
  - '@tiptap/extension-table@3.31.0'
  - '@tiptap/extension-text@3.31.0'
  - '@tiptap/extension-underline@3.31.0'
  - '@tiptap/extensions@3.31.0'
  - '@tiptap/markdown@3.31.0'
  - '@tiptap/pm@3.31.0'
  - '@tiptap/react@3.31.0'
  - '@tiptap/starter-kit@3.31.0'
