packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  node-liblzma: false
  protobufjs: false

catalog:
  '@iconify-json/catppuccin': ^1.2.17
  '@iconify/tailwind4': ^1.2.3
  vite-plus: ^0.2.4
