/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAiIndexRouteImport } from './routes/settings/ai/index'
import { Route as SettingsAiProvidersRouteImport } from './routes/settings/ai/providers'
import { Route as SettingsAiModelsRouteImport } from './routes/settings/ai/models'
import { Route as SettingsAiBasicRouteImport } from './routes/settings/ai/basic'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiIndexRoute = SettingsAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiProvidersRoute = SettingsAiProvidersRouteImport.update({
  id: '/ai/providers',
  path: '/ai/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiModelsRoute = SettingsAiModelsRouteImport.update({
  id: '/ai/models',
  path: '/ai/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiBasicRoute = SettingsAiBasicRouteImport.update({
  id: '/ai/basic',
  path: '/ai/basic',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/ai/basic': typeof SettingsAiBasicRoute
  '/settings/ai/models': typeof SettingsAiModelsRoute
  '/settings/ai/providers': typeof SettingsAiProvidersRoute
  '/settings/ai/': typeof SettingsAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/ai/basic': typeof SettingsAiBasicRoute
  '/settings/ai/models': typeof SettingsAiModelsRoute
  '/settings/ai/providers': typeof SettingsAiProvidersRoute
  '/settings/ai': typeof SettingsAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/ai/basic': typeof SettingsAiBasicRoute
  '/settings/ai/models': typeof SettingsAiModelsRoute
  '/settings/ai/providers': typeof SettingsAiProvidersRoute
  '/settings/ai/': typeof SettingsAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/logs'
    | '/settings/'
    | '/settings/ai/basic'
    | '/settings/ai/models'
    | '/settings/ai/providers'
    | '/settings/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/logs'
    | '/settings'
    | '/settings/ai/basic'
    | '/settings/ai/models'
    | '/settings/ai/providers'
    | '/settings/ai'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/logs'
    | '/settings/'
    | '/settings/ai/basic'
    | '/settings/ai/models'
    | '/settings/ai/providers'
    | '/settings/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai/': {
      id: '/settings/ai/'
      path: '/ai'
      fullPath: '/settings/ai/'
      preLoaderRoute: typeof SettingsAiIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai/providers': {
      id: '/settings/ai/providers'
      path: '/ai/providers'
      fullPath: '/settings/ai/providers'
      preLoaderRoute: typeof SettingsAiProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai/models': {
      id: '/settings/ai/models'
      path: '/ai/models'
      fullPath: '/settings/ai/models'
      preLoaderRoute: typeof SettingsAiModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai/basic': {
      id: '/settings/ai/basic'
      path: '/ai/basic'
      fullPath: '/settings/ai/basic'
      preLoaderRoute: typeof SettingsAiBasicRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAiBasicRoute: typeof SettingsAiBasicRoute
  SettingsAiModelsRoute: typeof SettingsAiModelsRoute
  SettingsAiProvidersRoute: typeof SettingsAiProvidersRoute
  SettingsAiIndexRoute: typeof SettingsAiIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAiBasicRoute: SettingsAiBasicRoute,
  SettingsAiModelsRoute: SettingsAiModelsRoute,
  SettingsAiProvidersRoute: SettingsAiProvidersRoute,
  SettingsAiIndexRoute: SettingsAiIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
